set -o noclobber -o nounset -o vi

alias uconf="git --git-dir=$HOME/.local/share/obsdconf.git --work-tree=$HOME"

export GPG_TTY="$(tty)"

alias vi=$EDITOR
alias ls='LC_COLLATE=C ls -p'
alias ll='ls -hl'
alias ff='find . -type f -name'
alias bc='bc -l'
alias ag='ag --pager=$PAGER'
alias gs='git status --short --branch || ls' gd='git diff'
alias gsh='git show' gl='git log --graph --pretty=log'
alias gco='git checkout' gb='git branch' gm='git merge' gst='git stash'
alias ga='git add' gmv='git mv' grm='git rm'
alias gc='git commit' gca='gc --amend' gt='git tag'
alias gp='git push' gu='git pull' gf='git fetch'
alias gr='git rebase' grc='git rebase --continue'
alias rand='openssl rand -base64 33'
alias private='eval "$(gpg -d ~/.private)"'

PS1='\w $ '
